// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB85Oj1Vs4xAr-PNjJHH4wfqB3QnnXX4nY',
    appId: '1:827540918245:web:ea02024222dc2bb5ae290c',
    messagingSenderId: '827540918245',
    projectId: 'restaurantflutter-b9e10',
    authDomain: 'restaurantflutter-b9e10.firebaseapp.com',
    storageBucket: 'restaurantflutter-b9e10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB85Oj1Vs4xAr-PNjJHH4wfqB3QnnXX4nY',
    appId: '1:827540918245:android:ea02024222dc2bb5ae290c',
    messagingSenderId: '827540918245',
    projectId: 'restaurantflutter-b9e10',
    storageBucket: 'restaurantflutter-b9e10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB85Oj1Vs4xAr-PNjJHH4wfqB3QnnXX4nY',
    appId: '1:827540918245:ios:ea02024222dc2bb5ae290c',
    messagingSenderId: '827540918245',
    projectId: 'restaurantflutter-b9e10',
    storageBucket: 'restaurantflutter-b9e10.firebasestorage.app',
    iosBundleId: 'com.example.flutterlogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB85Oj1Vs4xAr-PNjJHH4wfqB3QnnXX4nY',
    appId: '1:827540918245:ios:ea02024222dc2bb5ae290c',
    messagingSenderId: '827540918245',
    projectId: 'restaurantflutter-b9e10',
    storageBucket: 'restaurantflutter-b9e10.firebasestorage.app',
    iosBundleId: 'com.example.flutterlogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB85Oj1Vs4xAr-PNjJHH4wfqB3QnnXX4nY',
    appId: '1:827540918245:windows:ea02024222dc2bb5ae290c',
    messagingSenderId: '827540918245',
    projectId: 'restaurantflutter-b9e10',
    authDomain: 'restaurantflutter-b9e10.firebaseapp.com',
    storageBucket: 'restaurantflutter-b9e10.firebasestorage.app',
  );
}
